Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/Documents/code/byte_le_royale_2021/server/Server.py", line 131, in get_leaderboard
    abort(500, description="No data to return for leaderboard yet")
  File "/home/acm/.local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 940, in abort
    _aborter(status, *args, **kwargs)
  File "/home/acm/.local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 923, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: No data to return for leaderboard yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/acm/Documents/code/byte_le_royale_2021/server/Server.py", line 131, in get_leaderboard
    abort(500, description="No data to return for leaderboard yet")
  File "/home/acm/.local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 940, in abort
    _aborter(status, *args, **kwargs)
  File "/home/acm/.local/lib/python3.8/site-packages/werkzeug/exceptions.py", line 923, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: 500 Internal Server Error: No data to return for leaderboard yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/acm/Documents/code/byte_le_royale_2021/server/Server.py", line 72, in handle_exception
    response.data = json.dumps({
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InternalServerError is not JSON serializable
Error: No data to return for leaderboard
Exception in get_leaderboard: 500 Internal Server Error: No data to return for leaderboard yet
Error: No data to return for leaderboard
Exception in get_leaderboard: 500 Internal Server Error: No data to return for leaderboard yet
Error: No data to return for leaderboard
Exception in get_leaderboard: 500 Internal Server Error: No data to return for leaderboard yet
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return submissions_stats for d1965e2c-8614-4019-a37e-b190b03abf6c
Error: No data to return submissions_stats for d1965e2c-8614-4019-a37e-b190b03abf6c
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
ratelimit 5 per 1 minute (134.129.91.223) exceeded at endpoint: get_team_score_over_time
